### ISSUE TITLE
可以跨平台支持windows吗？

### ISSUE THREAD

**Issue by leoxxw** [IsoaSFlus/QLivePlayer#1]
您好：我想在windows实现这种功能，请问可以跨平台吗？
非常感谢！

**Comment by IsoaSFlus** [comment]
@leoxxw 
目前没有这种想法，因为windows下各个直播平台客户端已经很完善了。

**Comment by leoxxw** [comment]
比如qtav这种吗?我现在想要一个简洁版的直播流播放客户端，你说的windows下很完善，可以帮我举个例子吗？非常感谢。

**Comment by IsoaSFlus** [comment]
@leoxxw 抱歉我没有说清楚，我说的完善是直播平台官方的客户端。
不过如果你是要做一个简洁版的直播流播放客户端，你可以看看streamlink这个项目。
