### ISSUE TITLE
Core dumped on app startup.

### ISSUE THREAD

**Issue by nonabyte** [IsoaSFlus/QLivePlayer#11]
The app crashed immediately on startup without showing any GUI windows.
Neither _MarvelousBlack's_ qliveplayer-git package nor manual build via PKGBUILD from AUR works.
Error logs are as follows:

```
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland-org.kde.kwin.qpa, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
```

My system environment:
  - Arch Linux Latest
  - KDE Plasma 5.19.90
  - Qt 5.15.1

Related Dependencies:
- mpv-1:0.32.0-4
- ffmpeg-2:4.3.1-2 
- python-aiohttp-3.6.2-2 
- qt5-base-5.15.1-3 
- qt5-quickcontrols2-5.15.1-1 
- qt5-graphicaleffects-5.15.1-1 
- qt5-quickcontrols-5.15.1-1 
- python-3.8.6-1 
- ykdl-git-1.6.3.r180.e205959-1

**Comment by IsoaSFlus** [comment]
It's weird.
Did you try aur?

**Comment by nonabyte** [comment]
Sorry for bothering you, please just ignore this issue. 
I failed to realize that I was working on a headless remote workstation, instead of my own laptop.
Obviously, you can't connect to a display that does not exist XD.
