### ISSUE TITLE
不能播放斗鱼直播

### ISSUE THREAD

**Issue by jian-lin** [IsoaSFlus/QLivePlayer#13]
你好，我是gentoo系统。
编译安装后，能正常看B站，但是斗鱼看不了。ykdl能解析出斗鱼的链接。
用qlphelper会卡在这里：
```
$ qlphelper -d -u 'https://www.douyu.com/topic/EpicLeague?rid=3811559'
Finding stream...
Debug: streamer started (:0, )
Debug: danmaku launcher started (:0, )
Debug: ffmpeg started (:0, )
Debug: mpv started (:0, )
Debug: "https://play2.edgesrv.com/live/3811559rikG9MtpJ.flv?wsAuth=d887ff5ee913d1b661ee08520c6e389b&token=web-h5-0-3811559-84d40b4477b0da480fbeac8120eefa250854db930fc8aa07&logo=0&expire=0&did=6603c70307734258b1b367da94461c55&pt=2&st=0&vhost=play2&origin=ws&mix=0&isp=cmcc" (:0, )
```
此时能看到有mpv的进程
```
/usr/bin/mpv --idle=yes --player-operation-mode=pseudo-gui --cache=yes --vf=lavfi="fps=60" --input-ipc-server=/tmp/qlp-{e3920530-03f8-4c74-8d73-8fe17f83e728} /tmp/qlp-{3017ecf2-0a14-4114-8114-1482fa514f6a}
```
ctrl+c后的输出：
```
Bye!
Debug: streamlink exited!!!! (:0, )
Debug: waiting for ffmpeg exit! (:0, )
```

**Comment by IsoaSFlus** [comment]
用标准的链接试试

**Comment by jian-lin** [comment]
很迷，现在斗鱼也能正常播放了。
我刚才用`qlphelper -d -u `https://www.douyu.com/9999`试了一下，发现卡在这里：
```
$ qlphelper -d -u `qlphelper -d -u `https://www.douyu.com/9999`
Finding stream...
Debug: streamer started (:0, )
Debug: danmaku launcher started (:0, )
Debug: ffmpeg started (:0, )
Debug: mpv started (:0, )
```
和我之前用斗鱼9999试的输出不一样。之前用斗鱼9999试的时候，输出和我最开始发的类似。
感到有点奇怪，干后又试了一下B站直播。发现B站也会和斗鱼9999一样，卡在同一地方。
然后我重新编译，重启后，斗鱼、B站就也正常了。

最后，感谢作者写了这个项目，对我很有帮助。

**Comment by jian-lin** [comment]
找到原因了：默认的dns有问题，换了个dns服务器就正常了。

**Comment by goduck777** [comment]
我测试斗鱼也遇到一样的错误，其他的直播都没有问题。

```
% qlphelper -d -u "https://www.douyu.com/9999"
Finding stream...
Playing:  出去旅游放松几天，24号回来直播 - yyfyyf
Debug: start ffmpeg proc (:0, )
Debug: streamer started (:0, )
Debug: danmaku launcher started (:0, )
Debug: ffmpeg started (:0, )
Debug: mpv started (:0, )
```

**Comment by THMonster** [comment]
> 我测试斗鱼也遇到一样的错误，其他的直播都没有问题。
> 
> ```
> % qlphelper -d -u "https://www.douyu.com/9999"
> Finding stream...
> Playing:  出去旅游放松几天，24号回来直播 - yyfyyf
> Debug: start ffmpeg proc (:0, )
> Debug: streamer started (:0, )
> Debug: danmaku launcher started (:0, )
> Debug: ffmpeg started (:0, )
> Debug: mpv started (:0, )
> ```

你这啥版本的？

**Comment by goduck777** [comment]
> > 我测试斗鱼也遇到一样的错误，其他的直播都没有问题。
> > ```
> > % qlphelper -d -u "https://www.douyu.com/9999"
> > Finding stream...
> > Playing:  出去旅游放松几天，24号回来直播 - yyfyyf
> > Debug: start ffmpeg proc (:0, )
> > Debug: streamer started (:0, )
> > Debug: danmaku launcher started (:0, )
> > Debug: ffmpeg started (:0, )
> > Debug: mpv started (:0, )
> > ```
> 
> 你这啥版本的？

4.1.0

**Comment by goduck777** [comment]
之前的版本（4.0.1）也一样

**Comment by THMonster** [comment]
> 之前的版本（4.0.1）也一样

你能具体一点描述一下错误吗？我这没有问题诶。

**Comment by goduck777** [comment]
没有多余的错误信息，跟 @jian-lin 描述的一样。

我在美国，会不会是这个原因。

有没有办法显示streamfinder的错误信息。

**Comment by THMonster** [comment]
> 没有多余的错误信息，跟 @jian-lin 描述的一样。
> 
> 我在美国，会不会是这个原因。
> 
> 有没有办法显示streamfinder的错误信息。

你上面贴的debug信息来看，在拿真实链接阶段没有问题，问题大概在播放上，我估计和你在美国有关。
