### ISSUE TITLE
帮本项目在Gentoo的guru库中打了个包

### ISSUE THREAD

**Issue by jian-lin** [IsoaSFlus/QLivePlayer#14]
你好，我为这个项目在Gentoo的官方仓库[guru](https://wiki.gentoo.org/wiki/Project:GURU)中打了一个包：media-video/qliveplayer。
guru是Gentoo官方的仓库，主要由用户贡献打包，Gentoo开发者进行管理，有些类似Arch的AUR。
为Gentoo添加guru仓库的方法可以看[这里](https://wiki.gentoo.org/wiki/Eselect/Repository)。
希望能在readme中加上这个信息，方便大家在Gentoo下使用这个项目，谢谢。

**Comment by jian-lin** [comment]
比较巧合的是，我昨天打包到一半，你更新了版本，去掉了ykdl的依赖，帮我减少了额外的3个包的打包工作。

**Comment by IsoaSFlus** [comment]
很抱歉，现在才回复。
不过我不太清楚gentoo怎么使用。从你说的这个仓库安装的命令是什么呢？

**Comment by jian-lin** [comment]
1. 安装仓库管理工具

```bash
# emerge --ask app-eselect/eselect-repository
```

2. 刷新仓库列表

```bash
# eselect repository list
```

3. 添加`guru`仓库

```bash
# eselect repository enable guru
```

4. 同步`guru`仓库

```bash
# emerge --sync guru
```

5. 安装`qliveplayer`

```bash
# emerge --ask --verbose qliveplayer
```

**Comment by IsoaSFlus** [comment]
更新了readme，在里面加上了gentoo包的引导。非常感谢阁下打的包。
