### ISSUE TITLE
虎牙里那些循环播放的电影好像看不了

### ISSUE THREAD

**Issue by antizo** [IsoaSFlus/QLivePlayer#16]
一起看里的武林外传：https://www.huya.com/11352915
循环播放的，会很卡，断断续续，没办法看，游戏直播都挺好的。

**Comment by antizo** [comment]
Finding stream...
Finding stream...
Finding stream...
[艾繁06] /{zj/{zj/{zj/{zj/{zj/{zj
[-衡山后学祝小芸-] 靖哥哥
[Aaaa] 下一节舒服点是什么
[小小洋葱头] /{sq
[迷路了] /{sq/{sq/{sq/{sq/{sq/{sq/{sq
[小圆坏脾气] 几万人同时嗷呜/{sq/{sq/{sq
[传媒玩闹守护4团钻石会员] 🐯🐯🐯🐯🐯🐯🐯🐯🐯🐯🐯🐯🐯🐯🐯
[汐颜兮梦] /{sq/{sq/{sq/{sq
[弥海丶Cy] /{sq/{sq/{sq/{sq/{sq/{sq/{sq
[陈月半] 我没有经过
[卷卷盖乐世] /{sq/{sq/{sq/{sq/{sq/{sq/{sq/{sq/{sq/{sq/{sq/{sq
[chtywlzh] /{zj
[豆豆的心酸] 玉~
[蓝染] 这就是在虎牙看武林外传的好处
[劇終人散] /{sq/{sq/{sq/{sq/{sq/{sq/{sq/{
[宋胖子] /{sq/{sq/{sq/{sq/{sq/{sq/{sq
[道法自然] 什么就女流之辈了 男女平等呢
[可乐雪碧茶] 字幕君，出来挨打
[云梦漪] 😂😂😂😂😂😂😂
[拱猪的白菜] 字幕改了¿
[Bryce豪] 嗷呜
[脸红] 玉～
[托马斯小火车] 🐯
[别幻想，] 我居然舒服了
[Zero] /{sq/{sq/{sq/{sq/{sq/{sq
[鳗鱼饭] 玉～～～/{dk/{dk/{dk
[２８９７✦阿洋 ლ力挺一灯] 啊呜
[air] 下一个舒服点，迷你小壮士
[愁丶] 玉
[小小洋葱头] /{sq/{sq/{sq/{sq/{sq/{sq
[迪boss] /{sq/{sq/{sq/{sq/{sq/{sq/{sq/{sq/{sq
[不爱喝水的小茜姑娘] 几万人同时嗷呜，123早跑了
[羁] /{sq/{sq/{sq/{sq/{sq/{sq
[单纯爱自由] 我不是蜈蚣
[莫相伴梦已晚] 嗷~~~~~~
[李在赣神魔、] 那个老虎哪来的？
[虎牙使我快乐] /{sq/{sq/{sq
[我是一颗小虎牙] 以前有这歌？ 穿帮了啊
[请给我一杯奶茶] 笑场了
[２８９７✦阿洋 ლ力挺一灯] 啊呜
[传媒玩闹守护4团钻石会员] 😹😹😹😹😹😹😹😹😹😹😹😹😹😹😹
[没有认识我的人?] 玉
[狗酱] /{sq/{sq/{sq
[饮恨] /{sq/{sq/{sq/{sq/{sq/{sq/{sq[生
[过慧易夭] 没用的东西
[喂不熟的狗] 玉
[White-五开] 玉
Finding stream...
Finding stream...
Finding stream...
Finding stream...
[我是一颗小虎牙] 郭芙蓉行啊郭芙蓉
[喂不熟的狗] 玉
[七里客栈] 莫展堂
[沈梦溪本人] 夸你呢
Finding stream...
Finding stream...
Finding stream...
[﹎ゞ32oО] 小小郭多久来
Finding stream...
Finding stream...
Finding stream...
Bye!
Stream url not found!
QObject::startTimer: Timers can only be used with threads started with QThread

**Comment by IsoaSFlus** [comment]
对，那些放电影的都看不了，虎牙给这些直播间区别对待了，暂时拿不到他们的直播流。
