### ISSUE TITLE
[Feature Request] 读取默认弹幕设置

### ISSUE THREAD

**Issue by MrAru** [IsoaSFlus/QLivePlayer#17]
目前 QLivePlayer 的弹幕设置只能在打开一个 mpv 播放器后通过控制台手动更改当前播放器的弹幕大小及透明度。是否可以考虑在 `QLivePlayer/QLivePlayer.conf` 中增加 `fontscale` 及 `fontalpha` 字段，在每个 mpv 播放器打开时都读取该值？

**Comment by IsoaSFlus** [comment]
这个问题其实我一直在考虑，应该不久后就会解决这个问题

**Comment by IsoaSFlus** [comment]
新版本添加了此功能，你可以试试看是否正常。

**Comment by MrAru** [comment]
测试正常，非常感谢！
