### ISSUE TITLE
问题Stream url not found!

### ISSUE THREAD

**Issue by Net-red** [IsoaSFlus/QLivePlayer#25]
电脑配置
操作系统： Kubuntu 21.04
KDE Plasma 版本： 5.21.3
KDE 框架版本： 5.80.0
Qt 版本： 5.15.2
内核版本： 5.11.0-11-generic
操作系统类型： 64-位
图形平台： X11

问题如下图
![2021-03-25_19-02](https://user-images.githubusercontent.com/62368462/112464498-7a665800-8d5b-11eb-8817-7984b8a320bf.png)
之前因为qt版本不够,一直用的旧版
今天升级了一下,编译通过了,但是发现无法播放

**Comment by IsoaSFlus** [comment]
其他虎牙直播间能正常播放吗？

**Comment by Net-red** [comment]
> 其他虎牙直播间能正常播放吗？

现在可以正常播放了,刚装完时,在qliveplayer中点击历史记录还不行,现在都好了,玄学...
播放问题除了之前提过的虎牙一起看板块,别的没有问题
谢谢回复^~^
