### ISSUE TITLE
B站直播无法播放

### ISSUE THREAD

**Issue by goduck777** [IsoaSFlus/QLivePlayer#26]
我安装的3.22.1版本。B站的直播无法播放，Debug信息显示

curl exited (:0, )

我用你code里面的curl配置试了一下，B站返回403。

我发现的一个解决方法是加入在curl参数中加入Referer

参考： https://unix.stackexchange.com/questions/139698/why-would-curl-and-wget-result-in-a-403-forbidden

目前发现随便写一个referer都可以😶

不知道是不是只是我一个人的问题。如果可能的话，希望你在code里面加入referer，指向B站视频的网址。

**Comment by IsoaSFlus** [comment]
感觉可能是个例，因为我这b站直播工作正常。不过类似的问题在我写b站视频时出现过，所以b站视频链接的访问我是加了referer的。我下个版本把直播的referer也加上吧。

**Comment by goduck777** [comment]
谢谢。B站视频在我这里是没有问题的，只有直播不行，应该就是referer的问题。

**Comment by IsoaSFlus** [comment]
3.22.3版本加上了referer，你可以试试看有没有用。

**Comment by goduck777** [comment]
测试了一下3.22.3，现在直播和视频都没有问题了。谢谢！
