### ISSUE TITLE
历史记录界面直播间封面加载出现问题

### ISSUE THREAD

**Issue by MrAru** [IsoaSFlus/QLivePlayer#27]
![Screenshot_20210624_171922](https://user-images.githubusercontent.com/26517155/123243047-3844e200-d515-11eb-9c1f-0339433197ef.png)
如图所示, 正常开播的直播间在历史记录中的样式应该为标号 1 处所示; 如果未开播, 则如标号 2 处所示会将直播间标题改为 No title, 并正常显示开播者的名称. 但最近我经常遇见类似 3 处的情况, 直播间标题显示为 No title, 也没有开播者的名称, 左侧也不显示关键帧. 无论当前该直播是否正常推流 (即, 是否可用 `qlphelper -u` 获取推流并正常观看), 在 qliveplayer 的历史界面上都有可能出现这种情况. 而本来正常显示的直播间, 在 F5 刷新之后也可能变为这种状态. 而本来非正常的直播间, 在 F5 之后亦有可能变为正常. 希望能对这一情况进行调查.

相关版本
Arch Linux community/qliveplayer 3.22.1-1

**Comment by IsoaSFlus** [comment]
开没开播不看是不是No Title，看旁边那个绿条，是绿条就是开播，灰条就是没开播。你说的没出现直播主的情况，我今天好像也碰到好几次，据我观察都是虎牙的直播间，我最近看看是哪出了问题。

**Comment by MrAru** [comment]
感谢回复. 我又确认了几次, 发现在出现 3 这种情况时, 即使当前直播间正在直播, 绿条也是不显示的, 此时点击链接图标仍可以正常打开直播间. 我认为是在这种情况下绿条机制已经失效了, 无法通过其来判断当前是否开播. 另外我这边出现问题的也确实都是虎牙的直播间.

**Comment by IsoaSFlus** [comment]
别急，小问题，下个版本我一并修复

**Comment by IsoaSFlus** [comment]
原因我已经找到了，是huya更新了一些东西，数据的格式改变了。我已经适配了新的，但问题是他这个更新没有完全更新，有时候拿到的是新的，有时候拿到的是老的，所以还得观望一段时间。

**Comment by MrAru** [comment]
好的, 那就等待下个版本的修复了, 感谢调查 :smile:

**Comment by IsoaSFlus** [comment]
3.22.3版本已经push了，你可以试试看有没有解决这个问题

**Comment by MrAru** [comment]
新版本一切正常, 感谢修复~

Issue closed.
