### ISSUE TITLE
是不是只支持特定版本的qt

### ISSUE THREAD

**Issue by simonfire007** [IsoaSFlus/QLivePlayer#3]
系统Ubuntu，qt版本5.9.5
提示
qrc:/qml/main.qml:1:1: module "QtQuick" version 2.12 is not installed

**Comment by IsoaSFlus** [comment]
各个发行版拆包不同，我没法细写。只能写个qt
你这个从报错上来看是qml相关的包没装。
我没有ubuntu的设备，你自己到源里面装下相关的依赖试试看。

**Comment by simonfire007** [comment]
貌似确实和版本有关，我查到下面这个qt版本对应的文档，然后在源码里改变版本到2.2就没报这个错误了，改报其他的
下面是文档地址
https://doc.qt.io/qt-5/qtquickcontrols-index.html#versions

**Comment by IsoaSFlus** [comment]
感谢反馈，之后我斟酌一下把依赖版本改一改。
