### ISSUE TITLE
Invalid url!

### ISSUE THREAD

**Issue by qianyigengwu** [IsoaSFlus/QLivePlayer#4]
BV1wt4y1y7Bm
终端输出：
Invalid url!
qrc:/qml/HistoryPage.qml:14: TypeError: Cannot read property 'history_model' of null
qrc:/qml/SavedPage.qml:14: TypeError: Cannot read property 'saved_model' of null
QFileSystemWatcher::removePaths: list is empty
QFileSystemWatcher::removePaths: list is empty

**Comment by IsoaSFlus** [comment]
我这里能正常播放。
你是不是添加了cookie？

**Comment by qianyigengwu** [comment]
抱歉，什么叫添加了cookie？
如何删去呢？

**Comment by IsoaSFlus** [comment]
那看来不是这个问题。
你是怎么安装的？

**Comment by qianyigengwu** [comment]
1、编译安装
2、所有视频皆是如此

**Comment by IsoaSFlus** [comment]
贴一下你的`/usr/local/share/QLivePlayer`下面的文件

**Comment by qianyigengwu** [comment]
QLivePlayer / bili_url.py
QLivePlayer / dmc.pyz

**Comment by IsoaSFlus** [comment]
手动运行bili_url.py试试
`python bili_url.py https://www.bilibili.com/video/BV1wt4y1y7Bm`
然后把输出贴一下

**Comment by qianyigengwu** [comment]
Traceback (most recent call last):
  File "bili_url.py", line 5, in <module>
    import asyncio, aiohttp
ModuleNotFoundError: No module named 'aiohttp'

**Comment by qianyigengwu** [comment]
title:【睡前消息119】王石用别人的钱，给清华捐了53亿？ - 20200524 第一百一十九集
http://cn-hbwh2-cmcc-bcache-09.bilivideo.com/upgcxcode/51/55/194795551/194795551-1-80.flv?e=ig8euxZM2rNcNbKMhbUVhoMM7wNBhwdEto8g5X10ugNcXBB_&deadline=1590461740&gen=playurl&nbs=1&oi=1866235361&os=bcache&platform=html5&trid=9a2bfddeb75f425cb712ae330a14fad9&uipk=5&upsig=bde73c1d1df65111f0ea95ebc80dfa0e&uparams=e,deadline,gen,nbs,oi,os,platform,trid,uipk&mid=0

**Comment by qianyigengwu** [comment]
成功了

**Comment by qianyigengwu** [comment]
原因是我没装aiohttp
解决方案就是pip install aiohttp（<'_<'）。

**Comment by IsoaSFlus** [comment]
佛了，真就不看readme呗。
