### ISSUE TITLE
安装成功了，使用不了。

### ISSUE THREAD

**Issue by antizo** [IsoaSFlus/QLivePlayer#5]
lee@linux-1ej1:~> qliveplayer 
Cyclic dependency detected between "file:///usr/lib64/qt5/qml/org/kde/kirigami.2/styles/org.kde.desktop.plasma/Units.qml" and "file:///usr/lib64/qt5/qml/org/kde/kirigami.2/styles/org.kde.desktop.plasma/Units.qml"
QQmlExpression: Expression qrc:/qml/HistoryPage.qml:14:9 depends on non-NOTIFYable properties:
    RoomModel::history_model
QQmlExpression: Expression qrc:/qml/SavedPage.qml:14:9 depends on non-NOTIFYable properties:
    RoomModel::saved_model
QQmlExpression: Expression qrc:/qml/SavedPage.qml:14:9 depends on non-NOTIFYable properties:
    RoomModel::saved_model
QQmlExpression: Expression qrc:/qml/HistoryPage.qml:14:9 depends on non-NOTIFYable properties:
    RoomModel::history_model
QQmlExpression: Expression qrc:/qml/SavedPage.qml:14:9 depends on non-NOTIFYable properties:
    RoomModel::saved_model
QQmlExpression: Expression qrc:/qml/HistoryPage.qml:14:9 depends on non-NOTIFYable properties:
    RoomModel::history_model
Stream url not found!
/usr/local/bin/qlphelper: symbol lookup error: /usr/local/bin/qlphelper: undefined symbol: _ZdlPvm, version Qt_5
qliveplayer: symbol lookup error: qliveplayer: undefined symbol: _ZdlPvm, version Qt_5
lee@linux-1ej1:~> ql
qliveplayer  qlphelper    qlprecorder  
lee@linux-1ej1:~> qlphelper -u http://www.douyu.com/1144379
Stream url not found!
qlphelper: symbol lookup error: qlphelper: undefined symbol: _ZdlPvm, version Qt_5

操作系统： openSUSE Tumbleweed 20200617
KDE Plasma 版本： 5.19.0
KDE 框架版本： 5.71.0
Qt 版本： 5.15.0
内核版本： 5.7.1-1-default
操作系统类型： 64-位

**Comment by IsoaSFlus** [comment]
试试`qlphelper -u https://live.bilibili.com/3` 反馈下什么结果

**Comment by antizo** [comment]
> `qlphelper -u https://live.bilibili.com/3`

lee@linux-1ej1:~> qlphelper -u https://live.bilibili.com/3
qlphelper: symbol lookup error: qlphelper: undefined symbol: _ZdlPvm, version Qt_5

**Comment by IsoaSFlus** [comment]
感觉是编译时出了什么问题，具体我也不清楚。。。没碰到过这样的问题，要不你自己谷歌下找找答案。

**Comment by antizo** [comment]
> 感觉是编译时出了什么问题，具体我也不清楚。。。没碰到过这样的问题，要不你自己谷歌下找找答案。

qt网站下载最新的qt安装后，编译qliveplayer时候找不到/usr/include中的libdrm/GL/gl.h，于是将qt文件夹中的该文件直接拷贝了过来。之后编译安装都很顺利。

**Comment by IsoaSFlus** [comment]
喵喵喵？你为什么是从网站上下的qt？源里面的呢？

**Comment by antizo** [comment]
> 喵喵喵？你为什么是从网站上下的qt？源里面的呢？

的确是冲突了，删掉下载的qt，该从源安装之后，编译安装都异常顺利。
虎牙的直播可以打开，但是播放会断断续续，网络应该没问题的，弹幕也是显示正常的
斗鱼的就是直接Stream url not found!，看不了
你上面给出的b站的那个也是可以正常播放的。

**Comment by IsoaSFlus** [comment]
斗鱼看不了是因为ykdl的限制，由于斗鱼的加密，要想解析斗鱼的流地址，必须要安装一个js runtime，建议安装node。

**Comment by antizo** [comment]
> 斗鱼看不了是因为ykdl的限制，由于斗鱼的加密，要想解析斗鱼的流地址，必须要安装一个js runtime，建议安装node。

可以了。linux上看弹幕直播体验算是提升了许多了。

**Comment by Schr0dingerCat** [comment]
> > 喵喵喵？你为什么是从网站上下的qt？源里面的呢？
> 
> 的确是冲突了，删掉下载的qt，该从源安装之后，编译安装都异常顺利。
> 虎牙的直播可以打开，但是播放会断断续续，网络应该没问题的，弹幕也是显示正常的
> 斗鱼的就是直接Stream url not found!，看不了
> 你上面给出的b站的那个也是可以正常播放的。

opensuse源里怎么安装qt5阿？？？没找到

**Comment by antizo** [comment]
> > > 喵喵喵？你为什么是从网站上下的qt？源里面的呢？
> > 
> > 
> > 的确是冲突了，删掉下载的qt，该从源安装之后，编译安装都异常顺利。
> > 虎牙的直播可以打开，但是播放会断断续续，网络应该没问题的，弹幕也是显示正常的
> > 斗鱼的就是直接Stream url not found!，看不了
> > 你上面给出的b站的那个也是可以正常播放的。
> 
> opensuse源里怎么安装qt5阿？？？没找到

你是不是遇到qt5quick-config not found?
zypper in libQt5QuickControls2-5

**Comment by Schr0dingerCat** [comment]
@antizo 谢谢，需要安装 带-devel的。
其他的也都装了 nodejs也装了，但是运行仍然提示 Stream url not found!
希望@ @IsoaSFlus 能够出个docker，这样简单

**Comment by IsoaSFlus** [comment]
> @antizo 谢谢，需要安装 带-devel的。
> 其他的也都装了 nodejs也装了，但是运行仍然提示 Stream url not found!
> 希望@ @IsoaSFlus 能够出个docker，这样简单

你装了ykdl吗？
其次，不会出docker。

**Comment by Schr0dingerCat** [comment]
> > @antizo 谢谢，需要安装 带-devel的。
> > 其他的也都装了 nodejs也装了，但是运行仍然提示 Stream url not found!
> > 希望@ @IsoaSFlus 能够出个docker，这样简单
> 
> 你装了ykdl吗？
> 其次，不会出docker。

![Screenshot_20200621_123126](https://user-images.githubusercontent.com/16341312/85216764-3e145e80-b3bb-11ea-9e54-0bb1a75feea5.jpeg)
![Screenshot_20200621_123014](https://user-images.githubusercontent.com/16341312/85216768-4371a900-b3bb-11ea-8d34-c0828349f6ed.jpeg)
其他的也都装了

**Comment by Schr0dingerCat** [comment]
> 试试`qlphelper -u https://live.bilibili.com/3` 反馈下什么结果

我使用了，返回Stream url not found!

**Comment by antizo** [comment]
> > 试试`qlphelper -u https://live.bilibili.com/3` 反馈下什么结果
> 
> 
> 
> 我使用了，返回Stream url not found!

你这个是不是没安装？python-aiohttp
pip3 install aiohttp

**Comment by IsoaSFlus** [comment]
> > 试试`qlphelper -u https://live.bilibili.com/3` 反馈下什么结果
> 
> 我使用了，返回Stream url not found!

你`ykdl -i https://live.bilibili.com/3`看看

**Comment by Schr0dingerCat** [comment]
> > > 试试`qlphelper -u https://live.bilibili.com/3` 反馈下什么结果
> > 
> > 
> > 我使用了，返回Stream url not found!
> 
> 你`ykdl -i https://live.bilibili.com/3`看看

![Screenshot_20200621_132515](https://user-images.githubusercontent.com/16341312/85217391-ccd8a980-b3c2-11ea-97b2-5cb824f015b4.jpeg)
aiohttp 装了，这个是ykdl 的

**Comment by IsoaSFlus** [comment]
> > > > 试试`qlphelper -u https://live.bilibili.com/3` 反馈下什么结果
> > > 
> > > 
> > > 我使用了，返回Stream url not found!
> > 
> > 
> > 你`ykdl -i https://live.bilibili.com/3`看看
> 
> ![Screenshot_20200621_132515](https://user-images.githubusercontent.com/16341312/85217391-ccd8a980-b3c2-11ea-97b2-5cb824f015b4.jpeg)
> aiohttp 装了，这个是ykdl 的

你装的ykdl大概版本太老了，仔细看看他们项目的readme吧。

**Comment by Schr0dingerCat** [comment]
我直接git下来编译的。。。

**Comment by IsoaSFlus** [comment]
> 我直接git下来编译的。。。

**仔细看看他们项目的readme吧**

**Comment by antizo** [comment]
> 我直接git下来编译的。。。

pip3 install ykdl 
add ~/.local/bin to your PATH
里面不是有写吗，不需要自己去编译安装啊

**Comment by Schr0dingerCat** [comment]
> > 我直接git下来编译的。。。
> 
> pip3 install ykdl
> add ~/.local/bin to your PATH
> 里面不是有写吗，不需要自己去编译安装啊

我就是这也搞得阿

**Comment by Schr0dingerCat** [comment]
@IsoaSFlus 
我就是这么搞得，我说上面说编译说的不明白
pip3 install ykdl
add ~/.local/bin to your PATH

**Comment by IsoaSFlus** [comment]
> @IsoaSFlus
> 我就是这么搞得，我说上面说编译说的不明白
> pip3 install ykdl
> add ~/.local/bin to your PATH

你怎么还没理解我的意思。。。你应该先确保`ykdl`工作正常。如果ykdl工作不正常，你去发issue啊。。。
