### ISSUE TITLE
QlivePlayer中无法打开mpv图形界面

### ISSUE THREAD

**Issue by Net-red** [IsoaSFlus/QLivePlayer#6]
系统信息:
操作系统： Kubuntu 20.04
KDE Plasma 版本： 5.18.5
KDE 框架版本： 5.68.0
Qt 版本： 5.12.8
内核版本： 5.4.0-40-generic
操作系统类型： 64-位

编译安装都没有问题
`qlphelper -u https://live.bilibili.com/3`可以正确运行,调用mpv界面,并在终端显示弹幕

但在QlivePlayer中无法打开mpv图形界面,通过后台可以发现确实有mpv程序,但没画面,终端可以显示弹幕

**Comment by Net-red** [comment]
![image](https://user-images.githubusercontent.com/62368462/86503004-0fbe5800-bd99-11ea-955c-98f486746314.png)

这是调用qliveplayer的结果

**Comment by IsoaSFlus** [comment]
qliveplayer也不过是调用qlphelper罢了，既然你在qliveplayer输入直播间之后终端输出弹幕了，说明qlphelper启动成功了。而你说直接qlphelper播放是能正常播放的，那就很奇怪了，希望你能提供更多信息。

**Comment by Net-red** [comment]
> qliveplayer也不过是调用qlphelper罢了，既然你在qliveplayer输入直播间之后终端输出弹幕了，说明qlphelper启动成功了。而你说直接qlphelper播放是能正常播放的，那就很奇怪了，希望你能提供更多信息。

那怎么提供呢,

**Comment by IsoaSFlus** [comment]
多试几个直播间看看，每个都这样吗？最好把你的操作过程录制成视频我看看，单凭文字我怕实际情况和你说的有误差。

**Comment by Net-red** [comment]
我把程序重新安装一下,测试了一些直播.

虎牙:
大部分都可以,qlphelper和qliveplayer都可以了,
但个别的不行,一起看那个板块的好像都不行,调用qlphelper和qliveplayer后都只是在终端有弹幕

斗鱼&B站:
好像都可以

**Comment by Net-red** [comment]
![Peek 2020-07-04 11-42](https://user-images.githubusercontent.com/62368462/86504504-a5adaf00-bda8-11ea-9bbc-1ea1e1fc2143.gif)

**Comment by IsoaSFlus** [comment]
虎牙的那个分区是有点问题，似乎带了额外的验证，我试试看能不能修复吧

**Comment by Net-red** [comment]
![new](https://user-images.githubusercontent.com/62368462/86529944-1980b200-bea4-11ea-82f8-fb45fc00b231.gif)

新版本对应的虎牙一起看板块,终端会显示错误,mpv程序隔段时间才会出来,界面明显卡顿

别的直播没有问题

**Comment by IsoaSFlus** [comment]
。。。我还没修虎牙的一起看板块的问题，这个问题暂时不太好修。
