### ISSUE TITLE
B站视频无法播放，斗鱼直播卡顿

### ISSUE THREAD

**Issue by HSantu** [IsoaSFlus/QLivePlayer#7]
系统：Arch Linux
内核：5.7.7-arch1-1
桌面：Plasma
Qt 版本：5.15.0
QLivePlayer 版本  : 3.10.1.r0.gb5bbe0a-1
B站视频无法播放，报错 “Invalid url! ......segmentation fault (core dumped)......"，ykdl 可解析
![图片](https://user-images.githubusercontent.com/23703054/87045475-868ca280-c22a-11ea-9fd1-496cc6c58fa4.png)
![图片](https://user-images.githubusercontent.com/23703054/87045735-ceabc500-c22a-11ea-9930-4ef770003e9d.png)
另外，斗鱼直播最近经常出现卡顿，表现为 mpv 界面打开后只播放几秒钟直播就断开，需要反复打开数次才会正常，且有时会出现卡顿

**Comment by IsoaSFlus** [comment]
b站视频解析用的不是ykdl。。。
你手动试试吧，项目里面有个bili_url.py的python脚本
`python bili_url.py <bilibili_url>`
试试看什么输出

**Comment by HSantu** [comment]
输出为：
https://paste.ubuntu.com/p/dpbm7v9JpD/
https://paste.ubuntu.com/p/RggRV9nThD/

**Comment by IsoaSFlus** [comment]
那你这没问题啊
你之前是不是手动编译安装过？然后没卸载干净？

**Comment by HSantu** [comment]
没有啊，我一直是 ArchLinuxCN 源里装的

**Comment by IsoaSFlus** [comment]
那我也没办法了，因为我实在无法复现你的问题，我特意找了台干净的arch试了下，这两个视频都能正常放。而且你上面贴的两段输出来看，也都正常拿到链接了。建议你自己找一找原因，也许是因为你的环境有什么特殊性。

**Comment by HSantu** [comment]
好的，我再找下原因

**Comment by HSantu** [comment]
重装后间歇性可播放，且有时成功播放时会提示`QProcess: Destroyed while process ("ffmpeg") is still running.`，真是摸不着头脑......

**Comment by IsoaSFlus** [comment]
你放斗鱼卡顿的问题我觉得大概率是你的网的问题。尝试换一个运营商的网络试试看会不会卡

**Comment by HSantu** [comment]
你好，我根据报错关键字`segmentation fault (core dumped)`检索到一篇[文章](https://www.cnblogs.com/panfeng412/archive/2011/11/06/segmentation-fault-in-linux.html)，按照其中的提到的`dmesg`命令获取到`qlphelper[16099]: segfault at 2a5188a2c61b ip 0000559fe6cb0da7 sp 00007ffe75a486f0 error 4 in qlphelper[559fe6cad000+17000]`错误，使用`catchsegv`命令获取到[此错误](https://paste.ubuntu.com/p/dwVnnjfYFT/)。由于我不懂 C 语言，想麻烦你看下这是哪里出了问题

**Comment by IsoaSFlus** [comment]
源里面的没debug symbol 看不出啥东西。前面提示Invalid url的原因是没拿到视频的真实地址，后面的segfault反而不怎么重要。。。要不你上tg的archcn ot频道来找我吧，这gh issue节奏太慢了。

**Comment by HSantu** [comment]
好的，我在群里，请问要如何联系你

**Comment by IsoaSFlus** [comment]
私聊我吧 id:fourier
