### ISSUE TITLE
b站直播流获取

### ISSUE THREAD

**Issue by wuyu8512** [IsoaSFlus/QLivePlayer#9]
ykdl的获取改了，原画不是bd了

**Comment by IsoaSFlus** [comment]
能不能别做谜语人？

**Comment by wuyu8512** [comment]
啊这，我不知道咋说，结果上就是你这播放出来的不是原画，而是蓝光

**Comment by IsoaSFlus** [comment]
我这没问题，你自己检查ykdl版本

**Comment by wuyu8512** [comment]
ykdl最新的就是我提交的啊
https://live.bilibili.com/6
比如这个链接，原画码率是8000，你播放出来的码率只有3000

**Comment by IsoaSFlus** [comment]
![image](https://user-images.githubusercontent.com/5125031/88924911-73f40f00-d2a6-11ea-838d-914ee6604847.png)
ykdl的问题关我这啥事情？

**Comment by IsoaSFlus** [comment]
感觉你对我的项目有点误解，这里面并没有塞进一个ykdl，调用的是你系统的ykdl。

**Comment by IsoaSFlus** [comment]
看了下你的提交我懂你啥意思了，你是想说ykdl拿的b站直播流原来的原画变成了OG，但我这调用ykdl并不管这个，只要你的权重和顺序是对的就没问题。最离谱的是，你都不试一下就来发issue？

**Comment by wuyu8512** [comment]
两边都重新装了后没问题了，算我的锅吧

**Comment by IsoaSFlus** [comment]
我很怀疑你是不是linux用户。。。也就是说你压根没用过这个项目。。。
